### ISSUE TITLE
File webshare.host can not be upload

### ISSUE THREAD

**Issue by ronin-cz** [bckp/synology-webshare#2]
Hi,

I tried upload the "webshare.host" today and get en error "Hosting file is not valid".

My versions:
DSM 6.2.1-23824 Update 1
Download Station 3.8.12-3518

Any advice ?

Tomas

**Comment by bckp** [comment]
I will check, what can be issue... Have DSM 6.2.1 too...

**Comment by bckp** [comment]
@nemec-cz do you have some kind of ad-block? What version of Synology you have?
Check md5 for host file, should be: 78c653042cf67a89c3c26355533577f5

**Comment by ronin-cz** [comment]
Hi, I tried again today and it works. Can not say what was wrong. Thanks
