### ISSUE TITLE
Operace se nezdařila

### ISSUE THREAD

**Issue by vencam** [bckp/synology-webshare#3]
Na na Synology routeru RT2600 se SRM 1.2-7742 Update 5 v Download station verze 3.5-2991 to při ověření účtu napíše, že operace se nezdařila.

**Comment by bckp** [comment]
Díky za info, mrknu na to... jen pro ověření, jakou verzi pluginu máš?
Jenom pro info, předpokládám že účet je platný, spíše je otázka, nemáš v hesle nějaké speciální znaky nebo tak něco, abych mohl snadněji identifikovat, co je za problém...

**Comment by vencam** [comment]
Verze pluginu je 18.12. Ale je to trochu komplikovanější.  U download station pro NAS DSM plugin funguje, ale na routeru pro SRM nikoliv. Tam se download station liší číslem verze. Nevím jestli máte možnost to otestovat i na té verzi pro SRM. Heslo je normální (písmena, číslice). Díky.

**Comment by bckp** [comment]
No teď už nemám, protože jsem synology router už prodal... Každopádně, zkusím poladit a dám vědět.

**Comment by vencam** [comment]
To by bylo super. Díky.

**Comment by bckp** [comment]
Blbne i s poslední verzí?

**Comment by KossikCZ** [comment]
@bckp 
Teď jsem to na SRM zkoušel a bohužel i poslední verze zlobí a nepřihlásí / nestáhne. Download Station je tam ve verzi 3.5-2995. Je tam nějaká možnost logu, aby se dalo poznat, kde to neprojde?

Na DSM mi to přitom už pár let funguje skvěle (za to moc díky mimochodem). :)

**Comment by bckp** [comment]
Ahoj, chci si koupit zase synology router, protože mě současné Google řešení sere, takže možná za měsíc budu mít zařízení k dispozici a budu si moct více pohrát :)

**Comment by KossikCZ** [comment]
@bckp Ahoj, super. I kdyby ne a mohl jsem něco ověřit sám, stačí říct. Mam slušný vzorek čtyř RT2600 (+ čtyři MR2200), tak je na čem. :)
A jinak se moc nedivím, ve finále jsem taky rozumnější řešení jak od Synology nenašel (pokud člověk nepotřebuje VLAN). :)
Tak jako tak, předem moc díky.

**Comment by bckp** [comment]
Mno, pokud potřebuješ VLAN, stačí počkat až vyjde SRM 1.3 která bude přidávat podporu pro VLAN :-D jinak já jsem to teď jel na Google WIFI a spokojenost, ale teď mě google nasral, protože mě nutí přejít na Google Home, která neumí nastavit větší rozsah než 24 :/ takže pokud má někdo jako já 22kový rozsah na síti, tak už si nenastaví statické IP :/
Jinak moc slušná sbírka, já pujdu asi do RT2600 + MR2200

**Comment by bckp** [comment]
Tak už mám představu, co je špatně, problém je, že SRM nemá XML parser, takže nejsem schopen vyparsovat potřebná data, zkusím to přepsat na nějaký regulární výraz a uvidíme :) naštěstí Webshare nemá ty XML tak složité, takže by to mohlo běžet jak na SRM tak DSM. Ještě sranda, že je tam PHP verze 5.5 která je už pekelně dlouho nepodporovaná, Synology bude muset přinést s SRM 1.3 nějaké větší aktualizace, ideálně přejít na DSM7 jádro

**Comment by bckp** [comment]
@vencam @KossikCZ Zkuste experimentální verzi 22.04
https://github.com/bckp/synology-webshare/releases/tag/22.04

Musel jsem si trošku upravit configy v routeru abych se dostal k tomu co je špatně, tak potřebuju ověřit že je to OK i u někoho, kdo se nehrabal v konfiguraci synology PHP.

**Comment by KossikCZ** [comment]
@bckp U mě to bohužel končí opakovaně chybou. :( Akorát jsem nikde neobjevil, že by Download Station někam cokoliv logovalo, abych aspoň viděl cokoliv víc, než jen "chyba". :/ 

![Screenshot_20210419_223107_com android chrome_edit_47824180758848](https://user-images.githubusercontent.com/48318841/115299737-7ad9ef00-a15f-11eb-9bd1-e48c546a9b6d.jpg)

S tou PHP verzí teda dost překvapili. Mají co dohánět.

**Comment by bckp** [comment]
@KossikCZ a nastavil jsi ucet dobre? Musis mit tu verzi 22.04 + znovu nastavit ucet + klepni na overit... me to proslo bez potizi, proto me to prekvapuje :/

**Comment by bckp** [comment]
![image](https://user-images.githubusercontent.com/179652/115302095-52072900-a162-11eb-8ea4-4779e3a50094.png)

**Comment by bckp** [comment]
Kdyžtak povolit ssh, povolit admin účet, příhlásit se do aplikace jako root@IP, a pak
`cat /var/log/messages | tail -20`
A tam by mělo být, proč to neprošlo...

**Comment by KossikCZ** [comment]
@bckp Máš pravdu, jsem to ale vůl. Vyzkoušeno ještě jednou a vše šlape. 👌 Moc děkuji a zároveň promiň, že jsem tady nezaregistroval odpověď dřív. 🤦‍♂

**Comment by bckp** [comment]
Vpohodě :)
