### ISSUE TITLE
DS109 - nefunkční

### ISSUE THREAD

**Issue by Snowii123** [bckp/synology-webshare#5]
zdravím,

prvně díky za vaši práci!

Bohužel na prehistorické DS109 v Download Stationu hosta přidám bez problému, verifikace username+pass mi už ale hodí fail. Samotné stahovaní přes "Add" vložením přímého odkazu pak zůstane viset na "loadovací" ikonce a nikdy se nerozjede... Heslo je formátu písmen a čísel.

nějaké rady? 

Díky!

**Comment by bckp** [comment]
Zdravím,

zkusím připravit další verzi s nějakým logováním, aby se to dalo více odladit... zkusil bych ještě jiný účet, jestli není problém někde v hesle nebo něco podobného. Bohužel DS109 nemám k dispozici, takže nemůžu zkusit... jakou verzi DSM máte?

**Comment by Snowii123** [comment]
ok, to by bylo super! Rád maximálně pomůžu - jiný účet bohužel nemám, takže
tam moc nevím jak na to... Verze DSM je 4.2 - 3259 což je poslední co vyšel
a co asi kdy vyjde :)

Díky!

**Comment by bckp** [comment]
Zkusím stáhnout starší verzi Xpenology a ověřím, ale nic neslibuju, přece jenom, DSM 4.2 už je hodně stará verze... je možné, že tam prostě není dostatečně aktuální PHP...

**Comment by Snowii123** [comment]
jasna, v klidku, pujde pujde a kdyz ne tak holt ne :)

diky!
F

**Comment by bckp** [comment]
Tak se bojím že je to verzí PHP...

**Comment by Snowii123** [comment]
Takže už moc stará syno, je tak? Každopádně díky moc, že jste tomu věnoval
svůj čas!

FO

Dne st 2. 10. 2019 17:03 uživatel Radovan Kepák <notifications@github.com>
napsal:

**Comment by bckp** [comment]
Ano, je to prostě příliš staré :/
