### ISSUE TITLE
Synology DS218play

### ISSUE THREAD

**Issue by ArtMake** [bckp/synology-webshare#6]
**Dobrý den,**

přidal jsem webshare.host do aktuální verze Download Station a po stisknutí tlačítka "Ověřit" se vypíše hláška: "Účet nebo heslo není platné. Zkuste to znovu." Webové přihlášení k VIP účtu je funkční.

    Zařízení: **DS218play**
    Aktuální verze DMS: **DSM 6.2.2-24922 Update 2**

**Děkuji Vám za pomoc**

**Comment by bckp** [comment]
Jaká je verze pluginu prosím?

**Comment by ArtMake** [comment]
Instalovaná verze Pluginu je 19.05 ... Informace, která může pomoci je, že plugin pro stahování z Fastshare je funkční.

**Comment by bckp** [comment]
Zkuste prosím 22.04, mám podezření, že všechno způsobuje jedna příčina...

**Comment by bckp** [comment]
Pokud nepomůže, pak přihlásit se přes SSH, a spustit příkaz
`sudo cat /var/log/messages | tail -20`
