### ISSUE TITLE
Nefunguje stahování přes přímý odkaz (chyba task_status_not_supported_type)

### ISSUE THREAD

**Issue by zimaa77** [bckp/synology-webshare#8]
Pokud zadám na stahování přímý odkaz (https://vip.5.dl.webshare.cz/xxxx...), stahování skončí s chybou task_status_not_supported_type (stahování přes odkaz (https://webshare.cz/#/file/xxxx...) funguje bez problémů).

Bez tohoto dopňku naopak funguje jen stahování přes přímý odkaz. Ideálně bych potřeboval funkční obě varianty :) Děkuji.

**Comment by bckp** [comment]
Podívám se na to...

**Comment by bckp** [comment]
Vyřešeno v 20.05

**Comment by zimaa77** [comment]
Tak jsem to dnes zkusil, ale bohužel ne vždy ten přímý link obsahuje "vip", ale vypadá jen např. takto: https://9.dl.webshare.cz/8127/bGdLxyA8iE/...

**Comment by bckp** [comment]
Ajo, free user ho má jinak, upravím... sec...

**Comment by bckp** [comment]
https://github.com/bckp/synology-webshare/releases/tag/20.05.1
Zkuste a pokud to bude OK, vydám takto, dík moc

**Comment by zimaa77** [comment]
jo, vypadá, že funguje :) díky moc
